Update dependencies, analysis and fix WidgetsBinding.instance
TNorbury/reorderable_carousel pull request #2
Opened 2022-08-22 10:51 UTC by jocubeit

A series of commits that updates this excellent package to the most stable Flutter and new analysis using flutter_lints.

Also bumped the Version to 0.4.0.

Tests all pass.

Hope you can merge and publish this soon, I'd like to use it in a production release.

2022-08-22 23:18 UTC, TNorbury commented
Thanks for the PR, I'll take a look at this in the next few days!

2022-08-23 23:56 UTC, TNorbury requested changes
Thanks for your work, requested a few changes

2022-08-23 23:56 UTC, TNorbury commented on README.md
> +    reorderable_carousel: ^0.4.0
I have some other things I want to do before rolling out this release, so I'll handle all the version stuff
```suggestion
    reorderable_carousel: ^0.3.1
```

2022-08-23 23:56 UTC, TNorbury commented on analysis_options.yaml
> +    implementation_imports: false
please add back the removed rules
```suggestion
    implementation_imports: false
    constant_identifier_names: false
    omit_local_variable_types: false
    avoid_types_on_closure_parameters: false
    use_setters_to_change_properties: false
```

2022-08-23 23:56 UTC, TNorbury commented on pubspec.yaml
> +version: 0.4.0
I'll take care of the versioning
```suggestion
version: 0.3.2+1
```

2022-08-23 23:56 UTC, TNorbury commented on pubspec.yaml
> +  sdk: ">=2.17.0 <3.0.0"
This needs to stay in here to indicate that Flutter is required in order to use this package
```suggestion
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"
```

2022-08-23 23:56 UTC, TNorbury commented on pubspec.yaml
> +  flutter_lints:  ^2.0.0
alphabetize :)
```suggestion
  flutter_lints:  ^2.0.0
  flutter_test:
    sdk: flutter
```

2022-08-24 00:13 UTC, TNorbury commented on pubspec.yaml
> +  sdk: ">=2.17.0 <3.0.0"
I was incorrect here, it can be left as is.

2022-08-24 02:06 UTC, jocubeit commented
Thanks for reviewing and suggesting changes. All requests resolved.

2022-08-24 02:29 UTC, merged